### ISSUE TITLE
networkshare and dns settings

### ISSUE THREAD

**Issue by xCuzImPro** [Pr0meth3us/hms-docker#12]
can you give us a Example?
how about mounting?
edit /etc/hosts file, how? Example?

---

Can you give us an example?
How about incorporating?

how to edit the file / etc / hosts

**Comment by Pr0meth3us** [comment]
Not too sure what you mean. The ```setup.sh``` script handles both adding the mount to the ```/etc/fstab``` and adding the host entries to ```/etc/hosts``` automatically (if you choose Y when prompted to add to hosts file, this is mentioned twice in the readme).

You can edit each manually with the text editor of your choice. I personally prefer vim so I would use ```sudo vim /etc/hosts```
