### ISSUE TITLE
plex permission error

### ISSUE THREAD

**Issue by xCuzImPro** [Pr0meth3us/hms-docker#13]
`plex            | OSError: [Errno 13] Permission denied: '/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs'
plex            | Traceback (most recent call last):
plex            |   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py", line 168, in <module>
plex            |     run()
plex            |   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py", line 148, in run
plex            |     core = Framework.core.FrameworkCore(bundle_path, FRAMEWORK_DIR, config)
plex            |   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 130, in __init__
plex            |     self._setup_storage()
plex            |   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/core.py", line 305, in _setup_storage
plex            |     self.storage.ensure_dirs(log_dir)
plex            |   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 132, in ensure_dirs
plex            |     self.make_dirs(path)
plex            |   File "/usr/lib/plexmediaserver/Resources/Plug-ins-1e5ff713d/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 128, in make_dirs
plex            |     os.makedirs(path)
plex            |   File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/os.py", line 157, in makedirs
plex            |     mkdir(name, mode)
plex            | OSError: [Errno 13] Permission denied: '/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs'`

**Comment by Pr0meth3us** [comment]
Are you storing the config folder on a remote share?

**Comment by xCuzImPro** [comment]
no.

**Comment by Pr0meth3us** [comment]
Try removing the ```:ro``` at the end of line 291 in ```docker-compose.yml``` and let me know if that resolves it. This specifies that the Logs directory to be read-only for the container.

**Comment by xCuzImPro** [comment]
thx #closed
