### ISSUE TITLE
container.local connection refused

### ISSUE THREAD

**Issue by snoopy82481** [Pr0meth3us/hms-docker#15]
When attempting to access container.local, ex: plex.local, from the non-docker host I receive an error stating the connection was refused. I have the HOST file on that machine updated to reflect the changes for the host file on the non-docker host.  I can access the container using IPADDRESS:PORT but not able to using the container.local.  I was previously able to do this before I did a media server rebuild and used the newest git repository.   Let me know if you need something  from me and I will do my best to provide it.

**Comment by Pr0meth3us** [comment]
Probably related to issue #14 I found yesterday. I tried forcing Traefik v1.7 in the ```docker-compose.yml``` on my servers but I keep getting 404 errors and I don't know why, the traefik webpage is showing it's routing to the correct backend...

**Comment by Pr0meth3us** [comment]
Just made a small change to the ```docker-compose.yml``` file to force it to version 1.7 for traefik in the most recent commit, so just go ahead and pull the newest version of the repo and it _should_ work. 

Turns out I had made a small change in my traefik.toml file last night when trying to quickly convert to the traefik 2.0 version that I forgot about. Never do dev work in prod!

**Comment by snoopy82481** [comment]
Lol, I know that feeling.  Just run a "docker-compose up -d"?

**Comment by Pr0meth3us** [comment]
Yup!
 
Or if you changed the ```RESTARTPOLICY``` in the ```.env``` file (or using the setup script) from ```always```, it should also come back up with a reboot.

**Comment by snoopy82481** [comment]
That did the trick. Thank you for the quick response.  You have come a long way from when you first started this project, and it is showing in how well it is turning out.

**Comment by Pr0meth3us** [comment]
Thank you! People like you that submit issues or feature requests only help make it better!
