### ISSUE TITLE
[feature] Add SSL on top of nginx

### ISSUE THREAD

**Issue by siryur** [Pr0meth3us/hms-docker#5]
I like this setup, I think you could add SSL to it.
Just a simple of more lines on the docker-compose will do it if you use a docker image like letsencrypt-nginx-proxy-companion.

**Comment by Pr0meth3us** [comment]
The current nginx image, ```jwilder/nginx-proxy```, supports SSL but I'm not very familiar with SSL yet as I've only ever generated my own CA through pfSense and ran letsencrypt once before switching to CloudFlare. Everyone is requesting SSL so I'll definitely be looking into it shortly after ironing out some small bugs I just found and getting the basic-setup branch merged in.

**Comment by luketainton** [comment]
@Pr0meth3us Have you considered using Traefik? It handles reverse proxying a lot better and without much configuration.

**Comment by xCuzImPro** [comment]
https://github.com/jwilder/nginx-proxy/issues/601
https://github.com/jwilder/nginx-proxy/issues/366

**Comment by Pr0meth3us** [comment]
@luketainton A number of people mentioned Traefik on the reddit post so I'll definitely look into it. This is my first time using docker so I'm still working out how everything works and which containers would be best for what I want this to do.
